### PR TITLE
You were Drunk or so what ?

### PR DESCRIPTION
**Pull request by Captain-FLAM**
Read my code...

### CODE REVIEW

**Comment by Traumflug** [comment]
If you'd care to explain us what this commit changes, one might see the sense of it. Something like 
```
$data = json_decode($data, true);
```
should be entirely fine.

**Comment by yaniv14** [comment]
@Traumflug I think he got a good point.
this ```$data = json_decode($data, true);```
will cause $data value to get lost in this:
```
if ( ! $data) {
    $data = Tools::unSerialize($data);
}
```

**Comment by Traumflug** [comment]
> this ```$data = json_decode($data, true);```
> will cause $data value to get lost in this:
> ```
> if ( ! $data) {
>     $data = Tools::unSerialize($data);
> }
> ```
Yes, and that's actually wanted. Up to date data is encoded as JSON, data stored before the move to JSON is stored with PHP `serialize()`. Accordingly, try to decode as JSON first, and if this fails (result is empty), decode with `unserialize()`. A strategy called "retrocompatibility" (I like this word) in PS parlance.

**Comment by yaniv14** [comment]
@Traumflug I understand your intention for retrocompatibility, but you are missing the point.
when this ```$data = json_decode($data, true);``` returns null/empty than the original $data value is gone.
how can you unSerialize null? you will want to try and unSerialize the original $data value.

**Comment by Traumflug** [comment]
Now I get it. Thanks.

**Comment by Captain-FLAM** [comment]
Well done @yaniv14 :1st_place_medal: 

I was too busy to explain it ... Sorry

So now, you can merge it !

P.S : Next time, please think that if I pull a request, it's not accidentally ;-)

**Comment by Captain-FLAM** [comment]
Not yet integrated ???

**Comment by Traumflug** [comment]
Alright, picked to _master_ as 69933a5206601ec144e17749cd9da4ba55c82f0c. Thank you very much!

**Pull request closed without merging**
